name: build-test-bottleneck
description: "checkout repo, build, and test numpy"
runs:
  using: composite
  steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install
      shell: bash
      run: pip install . -v --group test

    - name: Test with pytest
      shell: bash
      run: |
        cd doc  # avoid picking up bottleneck from the source dir
        pytest --pyargs bottleneck
