name: build-test-bottleneck
description: "checkout repo, build, and test numpy"
runs:
  using: composite
  steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install
      shell: bash
      run: |
        pip install . -v

    - name: Test with pytest
      shell: bash
      run: |
        pip install pytest
        cd doc  # avoid picking up bottleneck from the source dir
        pytest --pyargs bottleneck
