name: build-test-bottleneck
description: "checkout repo, build, and test bottleneck"
runs:
  using: composite
  steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install
      shell: bash
      run: |
        uv sync --no-editable --group test ${{ case( endsWith(matrix.python-version, 't'), '--group concurrency', '' ) }}

    - name: Test with pytest
      shell: bash
      run: |
        cd doc  # avoid picking up bottleneck from the source dir
        uv run --no-sync pytest --pyargs bottleneck
