name: build-test-bottleneck
description: "checkout repo, build, and test numpy"
runs:
  using: composite
  steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: astral-sh/setup-uv@803947b9bd8e9f986429fa0c5a41c367cd732b41 # v7.2.1
      with:
        python-version: ${{ matrix.python-version }}
        prune-cache: false
    - name: Install
      shell: bash
      run: uv sync --no-editable --group test

    - name: Test with pytest
      shell: bash
      run: |
        cd doc  # avoid picking up bottleneck from the source dir
        uv run --no-sync pytest --pyargs bottleneck
