name: Github Actions

on: ["push", "pull_request"]

permissions: {}

jobs:
  test-linux-macos:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.10"
          - "3.14"
        os:
          - ubuntu-22.04
          - ubuntu-24.04-arm
          - macos-15-intel
          - macos-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: ./.github/bottleneck-action

  test-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.10"
          - "3.14"
          - "3.14t"
        architecture:
          - x86
          - x64
        os:
          - windows-latest
          - windows-2022
        include:
          - os: windows-11-arm
            architecture: arm64
            python-version: "3.11"
          - os: windows-11-arm
            architecture: arm64
            python-version: "3.14"
          - os: windows-11-arm
            architecture: arm64
            python-version: "3.14t"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: ./.github/bottleneck-action

  test-pyversions:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
         - "3.10"
         - "3.11"
         - "3.12"
         - "3.13"
         - "3.13t"
         - "3.14"
         - "3.14t"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: ./.github/bottleneck-action

  check:
    # This job is here is the "Required" one for merging PRs, and
    # it only runs after all the `test-*` jobs above have run. Hence
    # it serves as a check that CI actually ran before a PR gets merged.
    needs:
      - test-linux-macos
      - test-windows
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder for CI checks in PRs
        run: echo "Done"

  build_wheels:
    needs:
      - test-linux-macos
      - test-windows
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          archs: x86_64
          select: '*manylinux*'
        - os: ubuntu-latest
          archs: x86_64
          select: '*musllinux*'
        - os: ubuntu-24.04-arm
          archs: aarch64
          select: '*manylinux*'
        - os: ubuntu-24.04-arm
          archs: aarch64
          select: '*musllinux*'
        - os: macos-15-intel
          archs: x86_64
          select: '*'
        - os: macos-latest
          archs: arm64
          select: '*'
        - os: windows-latest
          archs: x86
          select: '*'
        - os: windows-latest
          archs: AMD64
          select: '*'
        - os: windows-11-arm
          archs: ARM64
          select: '*'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Build wheels
        uses: pypa/cibuildwheel@8d2b08b68458a16aeb24b64e68a09ab1c8e82084 # v3.4.1
        env:
          CIBW_ARCHS: ${{ matrix.archs }}
          CIBW_BUILD: ${{ matrix.select }}
        with:
          extras: uv
          output-dir: dist

      - name: Store wheel artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: dist/*.whl

  build_sdist:
    needs:
     - test-linux-macos
     - test-windows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          enable-cache: false

      - name: Build sdist
        run: uv build --sdist

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: dist/*.tar.gz

  release:
    needs:
      - build_wheels
      - build_sdist
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: dist
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0 # zizmor: ignore[use-trusted-publishing]
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN}}
